package version2;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;

/**
 *
 * @author Afsanat
 */
public class SHOWSTATS extends javax.swing.JFrame {

    /**
     * Creates new form SHOWSTATS
     */
    public SHOWSTATS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        largestdisplay = new javax.swing.JLabel();
        average = new javax.swing.JLabel();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        average1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LARGEST GALAMSEY");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("AVERAGE GALAMSEY COLOR VALUE");

        largestdisplay.setForeground(new java.awt.Color(0, 0, 0));
        largestdisplay.setText("VALUE");

        average.setForeground(new java.awt.Color(0, 0, 0));
        average.setText("AVERAGE");


        jButton1.setForeground(new java.awt.Color(200, 2, 2));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }

        });

        average1.setForeground(new java.awt.Color(0, 0, 0));
        average1.setText("STATISTICS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(average1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(largestdisplay)
                    .addComponent(average))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(average1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(largestdisplay))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(average))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }


    public void showStats() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SHOWSTATS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SHOWSTATS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SHOWSTATS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SHOWSTATS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SHOWSTATS().setVisible(true);

            }
        });

        java.sql.Connection connect = null;


        System.out.println("Displaying information to the console");
        try {
            connect = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/Galamseys?user=root&password=admin");
        } catch (Exception e) {
            System.out.println(e);
            System.exit(0);
        }
        System.out.println("It is connected");
        try {
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet res = stm.executeQuery("SELECT * FROM Galamsey");
            System.out.println("Here is what is in Galamsey table: (1:Galamsey id, 2:GalamseyName,3:vegetationColor,4:year,5:latitude,6:longitude)");
            while (res.next()) {
                System.out.println(res.getString("Galamseyid") + " \t" + res.getString("GalamseyName") + " \t" + res.getString("VegetationColor") + " \t" + res.getString("Year_of_event")+ " \t" +res.getString("latitude") + " \t"+ res.getString("longitude"));
            }
            System.out.println();

            java.sql.Statement stm2 = connect.createStatement();
            java.sql.ResultSet res2 = stm.executeQuery("SELECT * FROM Observatory");
            System.out.println("Here is what is in observatory table: (1:observatory id, 2: galamsey id, 3:observatory Name, 4:country, 5:year, 6:area)");
            while (res2.next()) {
                System.out.println(res2.getString("observatoryid") + " \t" + res2.getString("Galamseyid") + " \t"+ res2.getString("observatoryName") + " \t" + res2.getString("country") + " \t" + res2.getString("yearofObservation")+ " \t" +res2.getString("area"));
            }

            res2.close();
            stm2.close();
            connect.close();
        } catch (Exception e) {
            System.out.println(e);
            System.exit(0);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel average;
    private javax.swing.JLabel average1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel largestdisplay;
    // End of variables declaration//GEN-END:variables
}
